In [158]:
import numpy as np
print(np.__version__)

1.25.2


In [159]:
import numpy as np   # as use in short name
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distribut

In [160]:
import numpy as np 
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [161]:
# array properties (dimanstion)
a.ndim


1

In [162]:
# find element in array  "," define tuple 
a.shape

(4,)

In [163]:
import numpy as np 
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [164]:
a.shape  # first use in array dimestion and second define that number of element in array

(2, 4)

In [165]:
a.ndim

2

In [166]:
import numpy as np 
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [167]:
a.shape

(4,)

In [168]:
a.ndim

1

In [169]:
#create an array of shape (3,1,2)
import numpy as np 
a=np.array([[[1,2]],[[1,2]],[[1,2]]])
print(a)

[[[1 2]]

 [[1 2]]

 [[1 2]]]


In [170]:
a.shape

(3, 1, 2)

In [171]:
#create an array of shape (5,4)
import numpy as np 
a=np.array([[1,2,3,4],[5,6,7,8],[1,2,3,4],[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]]


In [172]:
a.shape

(5, 4)

In [173]:
import numpy as np
z=np.zeros(5)
print(z)

[0. 0. 0. 0. 0.]


In [174]:
type(z)

numpy.ndarray

In [175]:
import numpy as np
z=np.zeros(5,dtype=np.int8)
print(z)

[0 0 0 0 0]


In [176]:
import numpy as np
z=np.zeros([3,4])
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [177]:
import numpy as np
z=np.zeros([3,4],dtype=np.int8)
print(z)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [178]:
import numpy as np  #use only 1-d array
z=np.arange(10,20)
print(z)

[10 11 12 13 14 15 16 17 18 19]


In [179]:
import numpy as np
z=np.linspace(1,2,num=50)
print(z)

[1.         1.02040816 1.04081633 1.06122449 1.08163265 1.10204082
 1.12244898 1.14285714 1.16326531 1.18367347 1.20408163 1.2244898
 1.24489796 1.26530612 1.28571429 1.30612245 1.32653061 1.34693878
 1.36734694 1.3877551  1.40816327 1.42857143 1.44897959 1.46938776
 1.48979592 1.51020408 1.53061224 1.55102041 1.57142857 1.59183673
 1.6122449  1.63265306 1.65306122 1.67346939 1.69387755 1.71428571
 1.73469388 1.75510204 1.7755102  1.79591837 1.81632653 1.83673469
 1.85714286 1.87755102 1.89795918 1.91836735 1.93877551 1.95918367
 1.97959184 2.        ]


In [180]:
import numpy as np
z=np.linspace(1,2,num=5,endpoint=False)
print(z)

[1.  1.2 1.4 1.6 1.8]


In [181]:
import numpy as np
z=np.array([np.arange(1,5),np.arange(11,15)])
print(z)
print("print first row")

[[ 1  2  3  4]
 [11 12 13 14]]
print first row


In [182]:
import numpy as np
z=np.array([np.arange(1,5),np.arange(11,15)])
print(z)
print("print second row")
print(z[1,2])   #use in indexing in row
print(z[1][2])

[[ 1  2  3  4]
 [11 12 13 14]]
print second row
13
13


In [183]:
import numpy as np
z=np.array([np.arange(1,5),np.arange(11,15)])
print(z)
print("print sub array")
print(z[:,1:3])   

[[ 1  2  3  4]
 [11 12 13 14]]
print sub array
[[ 2  3]
 [12 13]]


In [184]:
z.shape

(2, 4)

In [185]:
z.ndim

2

In [186]:
import numpy as np
z=np.array(np.arange(1,37)).reshape(3,4,3)
print(z)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]


In [187]:
a=z.reshape(3,4,3)
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]],

       [[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [188]:
import numpy as np
z=np.array(np.arange(1,37))
c=np.reshape(z,(3,4,3))
print(c)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]


In [189]:
import numpy as np
z=np.array(np.arange(1,37)).reshape(3,4,3).transpose()
z

array([[[ 1, 13, 25],
        [ 4, 16, 28],
        [ 7, 19, 31],
        [10, 22, 34]],

       [[ 2, 14, 26],
        [ 5, 17, 29],
        [ 8, 20, 32],
        [11, 23, 35]],

       [[ 3, 15, 27],
        [ 6, 18, 30],
        [ 9, 21, 33],
        [12, 24, 36]]])

In [190]:
import numpy as np
z=np.array(np.arange(1,37)).reshape(3,4,3)
print(z[::2,1::2,1::2])

[[[ 5]
  [11]]

 [[29]
  [35]]]


In [191]:
import numpy as np
n=np.array([11,25,14,23	,14	,22	,13	,30	,7	,26	,9	,24	,12	,26,15,29,13,31,8,25,-13,29,11,29,6,23,13,23,11,25,11,23,6,26,10,30,9,32,10,25,6,24,15,20,13,23,8,28,11,24,12,24,6,28,9,27,14,32,15,32,11,23,13,27,11,26,10,31,9,20,9,32,14,32,9,24,12,28,10,25,6,32,13,21,8,26,11,23,15,28,14,27,6,22,8,29,15,28,])

n

array([ 11,  25,  14,  23,  14,  22,  13,  30,   7,  26,   9,  24,  12,
        26,  15,  29,  13,  31,   8,  25, -13,  29,  11,  29,   6,  23,
        13,  23,  11,  25,  11,  23,   6,  26,  10,  30,   9,  32,  10,
        25,   6,  24,  15,  20,  13,  23,   8,  28,  11,  24,  12,  24,
         6,  28,   9,  27,  14,  32,  15,  32,  11,  23,  13,  27,  11,
        26,  10,  31,   9,  20,   9,  32,  14,  32,   9,  24,  12,  28,
        10,  25,   6,  32,  13,  21,   8,  26,  11,  23,  15,  28,  14,
        27,   6,  22,   8,  29,  15,  28])

In [192]:



12,31,13,23,12,20,7,21,8,23,15,24,8,27,6,21,7,18,3,22,3,18,3,18,3,4,19,4,6,21,5,20,7,21,4,19,8,19,3,3,18,7,7,20,2,18,6,21,8,22,5,22,6,6,22,2,
8,20,3,18,7,19,2,21,7,20,2,3,18,7,12,21,8,18,-10,21,11,20,9,22,11,71,21,8,10,22,7,21,12,22,9,20,8,21,9,7,19,9,11,22,7,18,10,18,8,21,9,18,8,10,19,7,
7,20,7,20,8,22,10,21,9,18,9,9,22,9

(7, 20, 7, 20, 8, 22, 10, 21, 9, 18, 9, 9, 22, 9)

In [193]:
import numpy as np
n=np.array([6,20,14,26,9,20,11,24,6,21,10,30,14,27,10,28,9,30,6,20,-13,32,7,27,11,30,10,21,7,30,6,32,12,20,8,31,10,21,13,32,12,24,6,22,7,21,13,22,11,24,7,21,8,31,14,30,15,22,10,28,11,26,15,22,11,27,9,22,9,21,14,22,10,30,7,31,11,28,7,30,8,23,7,22,10,26,10,32,8,31,11,26,15,23,8,21,15,21,10,21,9,32,9,25,8,30,8,22,13,30,6,21,4,22,8,20,5,22,3,18,4,20,6,2,20,8,6,19,7,22,3,22,6,21,2,21,3,3,19,4,4,20,7,21,8,21,3,18,7,18,3,3,20,3,4,22,7,21,5,18,7,22,4,20,3,5,18,2,7,18,8,22,-10,21,9,20,8,21,12,71,21,9,11,20,11,18,11,19,12,20,11,19,11,7,20,10,7,20,9,19,11,22,8,21,11,20,12,10,20,8,8,21,12,19,11,19,11,22,11,20,7,10,20,8]).reshape(16,14)
print(n)

[[  6  20  14  26   9  20  11  24   6  21  10  30  14  27]
 [ 10  28   9  30   6  20 -13  32   7  27  11  30  10  21]
 [  7  30   6  32  12  20   8  31  10  21  13  32  12  24]
 [  6  22   7  21  13  22  11  24   7  21   8  31  14  30]
 [ 15  22  10  28  11  26  15  22  11  27   9  22   9  21]
 [ 14  22  10  30   7  31  11  28   7  30   8  23   7  22]
 [ 10  26  10  32   8  31  11  26  15  23   8  21  15  21]
 [ 10  21   9  32   9  25   8  30   8  22  13  30   6  21]
 [  4  22   8  20   5  22   3  18   4  20   6   2  20   8]
 [  6  19   7  22   3  22   6  21   2  21   3   3  19   4]
 [  4  20   7  21   8  21   3  18   7  18   3   3  20   3]
 [  4  22   7  21   5  18   7  22   4  20   3   5  18   2]
 [  7  18   8  22 -10  21   9  20   8  21  12  71  21   9]
 [ 11  20  11  18  11  19  12  20  11  19  11   7  20  10]
 [  7  20   9  19  11  22   8  21  11  20  12  10  20   8]
 [  8  21  12  19  11  19  11  22  11  20   7  10  20   8]]


In [194]:
n.ndim

2

In [195]:
n.shape

(16, 14)

In [196]:
import numpy as np
a=np.array([6,20,14,26,9,20,11,24,6,21,10,30,14,27,10,28,9,30,6,20,-13,32,7,27,11,30,10,21,7,30,6,32,12,20,8,31,10,21,13,32,12,24,6,22,7,21,13,22,11,24,7,21,8,31,14,30,15,22,10,28,11,26,15,22,11,27,9,22,9,21,14,22,10,30,7,31,11,28,7,30,8,23,7,22,10,26,10,32,8,31,11,26,15,23,8,21,15,21,10,21,9,32,9,25,8,30,8,22,13,30,6,21,4,22,8,20,5,22,3,18,4,20,6,2,20,8,6,19,7,22,3,22,6,21,2,21,3,3,19,4,4,20,7,21,8,21,3,18,7,18,3,3,20,3,4,22,7,21,5,18,7,22,4,20,3,5,18,2,7,18,8,22,-10,21,9,20,8,21,12,71,21,9,11,20,11,18,11,19,12,20,11,19,11,7,20,10,7,20,9,19,11,22,8,21,11,20,12,10,20,8,8,21,12,19,11,19,11,22,11,20,7,10,20,8]).reshape(16,14)
print(a)

[[  6  20  14  26   9  20  11  24   6  21  10  30  14  27]
 [ 10  28   9  30   6  20 -13  32   7  27  11  30  10  21]
 [  7  30   6  32  12  20   8  31  10  21  13  32  12  24]
 [  6  22   7  21  13  22  11  24   7  21   8  31  14  30]
 [ 15  22  10  28  11  26  15  22  11  27   9  22   9  21]
 [ 14  22  10  30   7  31  11  28   7  30   8  23   7  22]
 [ 10  26  10  32   8  31  11  26  15  23   8  21  15  21]
 [ 10  21   9  32   9  25   8  30   8  22  13  30   6  21]
 [  4  22   8  20   5  22   3  18   4  20   6   2  20   8]
 [  6  19   7  22   3  22   6  21   2  21   3   3  19   4]
 [  4  20   7  21   8  21   3  18   7  18   3   3  20   3]
 [  4  22   7  21   5  18   7  22   4  20   3   5  18   2]
 [  7  18   8  22 -10  21   9  20   8  21  12  71  21   9]
 [ 11  20  11  18  11  19  12  20  11  19  11   7  20  10]
 [  7  20   9  19  11  22   8  21  11  20  12  10  20   8]
 [  8  21  12  19  11  19  11  22  11  20   7  10  20   8]]


In [197]:
import numpy as np
a=np.array([6,20,14,26,9,20,11,24,6,21,10,30,14,27,10,28,9,30,6,20,-13,32,7,27,11,30,10,21,7,30,6,32,12,20,8,31,10,21,13,32,12,24,6,22,7,21,13,22,11,24,7,21,8,31,14,30,15,22,10,28,11,26,15,22,11,27,9,22,9,21,14,22,10,30,7,31,11,28,7,30,8,23,7,22,10,26,10,32,8,31,11,26,15,23,8,21,15,21,10,21,9,32,9,25,8,30,8,22,13,30,6,21,4,22,8,20,5,22,3,18,4,20,6,2,20,8,6,19,7,22,3,22,6,21,2,21,3,3,19,4,4,20,7,21,8,21,3,18,7,18,3,3,20,3,4,22,7,21,5,18,7,22,4,20,3,5,18,2,7,18,8,22,-10,21,9,20,8,21,12,71,21,9,11,20,11,18,11,19,12,20,11,19,11,7,20,10,7,20,9,19,11,22,8,21,11,20,12,10,20,8,8,21,12,19,11,19,11,22,11,20,7,10,20,8]).reshape(4,4,7,2)
print(a)

[[[[  6  20]
   [ 14  26]
   [  9  20]
   [ 11  24]
   [  6  21]
   [ 10  30]
   [ 14  27]]

  [[ 10  28]
   [  9  30]
   [  6  20]
   [-13  32]
   [  7  27]
   [ 11  30]
   [ 10  21]]

  [[  7  30]
   [  6  32]
   [ 12  20]
   [  8  31]
   [ 10  21]
   [ 13  32]
   [ 12  24]]

  [[  6  22]
   [  7  21]
   [ 13  22]
   [ 11  24]
   [  7  21]
   [  8  31]
   [ 14  30]]]


 [[[ 15  22]
   [ 10  28]
   [ 11  26]
   [ 15  22]
   [ 11  27]
   [  9  22]
   [  9  21]]

  [[ 14  22]
   [ 10  30]
   [  7  31]
   [ 11  28]
   [  7  30]
   [  8  23]
   [  7  22]]

  [[ 10  26]
   [ 10  32]
   [  8  31]
   [ 11  26]
   [ 15  23]
   [  8  21]
   [ 15  21]]

  [[ 10  21]
   [  9  32]
   [  9  25]
   [  8  30]
   [  8  22]
   [ 13  30]
   [  6  21]]]


 [[[  4  22]
   [  8  20]
   [  5  22]
   [  3  18]
   [  4  20]
   [  6   2]
   [ 20   8]]

  [[  6  19]
   [  7  22]
   [  3  22]
   [  6  21]
   [  2  21]
   [  3   3]
   [ 19   4]]

  [[  4  20]
   [  7  21]
   [  8  21]
   [  3  18]
   [  7  18]
 

In [198]:
import numpy as np
a= np.array([np.arange(1,6),np.arange(11,16)])
print(a)

[[ 1  2  3  4  5]
 [11 12 13 14 15]]


In [199]:
a.shape

(2, 5)

In [200]:
print(a[0,1])
print((a[0,1:4]))

2
[2 3 4]


In [201]:
import numpy as np
a =np.array([1,3,2,1,6,5,3,9])
l=[4,5,7]
print(a[l])

[6 5 9]


In [202]:
import numpy as np
a =np.array([1,3,2,1,6,5,3,9])
b=np.array([False,False,False,False,True,True,False,True]) #use in filtering
print(a[b])

[6 5 9]


In [203]:
import numpy as np
a =np.array([1,3,2,1,6,5,3,9])
b=a>3
print(b)
print(a[b])

[False False False False  True  True False  True]
[6 5 9]


In [204]:
import numpy as np
a =np.array([1,3,2,1,6,5,3,9])
b=a.reshape((2,4))
print(b)

[[1 3 2 1]
 [6 5 3 9]]


In [205]:
import numpy as np
a =np.array([1,3,2,1,6,5,3,9])
b=a.reshape(2,4)
x=101
y=x
y=9
print(x,y)
print(a)
print()
print(b)

b[0]=44
print("b:",b)
print()
print("a:",a)

101 9
[1 3 2 1 6 5 3 9]

[[1 3 2 1]
 [6 5 3 9]]
b: [[44 44 44 44]
 [ 6  5  3  9]]

a: [44 44 44 44  6  5  3  9]


In [206]:
import numpy as np
a =np.array([1,3,2,1,6,5,3,9])
b=a[2:4]
x=101
y=x
y=9
print(x,y)
print(a)
print()
print(b)

b[0]=44
print("b:",b)
print()
print("a:",a)

101 9
[1 3 2 1 6 5 3 9]

[2 1]
b: [44  1]

a: [ 1  3 44  1  6  5  3  9]


In [207]:
import numpy as np
a =np.array([1,3,2,1,6,5,3,9])
b=a.reshape((2,4)).copy()

print(a)
print()
print(b)

b[0]=44
print("b:",b)
print()
print("a:",a)

[1 3 2 1 6 5 3 9]

[[1 3 2 1]
 [6 5 3 9]]
b: [[44 44 44 44]
 [ 6  5  3  9]]

a: [1 3 2 1 6 5 3 9]


In [208]:
import numpy as np
#sum,mean,var,std,prod,min,max,all,any
a=np.array([[1,2,3],[3,3,4]]) #marks of a student in 3 subject taken different test
print(a)

print()
total=np.sum(a)
total1=np.sum(a, axis=0)
total2=np.sum(a, axis=1)  #total ka liya
print(total)
print(total1)
print(total2)

[[1 2 3]
 [3 3 4]]

16
[4 5 7]
[ 6 10]


In [209]:
import numpy as np
a=np.array([[1,2,3],[3,3,4]]) 
print(a)

print()

total=np.sum(a, axis=0)
avg=round(np.mean(a,dtype=np.float32),ndigits=2)

print(total)
print("mean:",avg)

[[1 2 3]
 [3 3 4]]

[4 5 7]
mean: 2.67


In [210]:
import numpy as np
n=np.array([[5,3,9],[9,8,6],[1,3,5]])
print(np.mean(n,where=[[True],[False],[False]]))

5.666666666666667


In [211]:
import numpy as np
a=np.arange(1,37).reshape(4,9)
print(a)

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36]]


In [212]:
import numpy as np
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distribut

In [213]:
import numpy as np
a=np.arange(1,37).reshape(4,9)
c=a.flatten()
print(c)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]


In [214]:
import numpy as np
a=np.arange(1,37).reshape(4,9)
c=a.flatten(order='F')
print(c)

[ 1 10 19 28  2 11 20 29  3 12 21 30  4 13 22 31  5 14 23 32  6 15 24 33
  7 16 25 34  8 17 26 35  9 18 27 36]


In [215]:
import numpy as np
a=np.arange(1,37).reshape(4,9)
c=a.flatten(order='k')
print(c)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]


In [216]:
import numpy as np
a=np.arange(1,37).reshape(2,2,9)
c=np.ravel(a,order='f')
print(c)

[ 1 19 10 28  2 20 11 29  3 21 12 30  4 22 13 31  5 23 14 32  6 24 15 33
  7 25 16 34  8 26 17 35  9 27 18 36]


In [217]:
import numpy as np
a=np.arange(1,7).reshape(2,3)
b=np.arange(11,17).reshape(2,3)

print(a)
print(b)
#c=a+b
#print(c)

#c=np.concatenate((a,b),axis=1)     #add to array
c=np.stack((a,b),axis=1)
print(c)

[[1 2 3]
 [4 5 6]]
[[11 12 13]
 [14 15 16]]
[[[ 1  2  3]
  [11 12 13]]

 [[ 4  5  6]
  [14 15 16]]]


In [218]:
import numpy as np
a=np.arange(1,7)
b=np.arange(11,17)

print(a)
print(b)
#c=a+b
#print(c)

#c=np.concatenate((a,b),axis=1)     #add to array
c=np.stack((a,b),axis=1)
print(c)

[1 2 3 4 5 6]
[11 12 13 14 15 16]
[[ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]
 [ 6 16]]


In [226]:
import numpy as np
a=np.arange(1,28).reshape(3,3,3)
b=np.arange(11,20).reshape(1,3,3)

print(a)
print(b)
# it use in horizontaly   c=np.hstack((a,b))
print(c)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[11 12 13]
  [14 15 16]
  [17 18 19]]]
[[ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]
 [ 6 16]]


In [236]:
import numpy as np
a=np.arange(1,28)
#split method

s=np.split(a,27)
print(s)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([7]), array([8]), array([9]), array([10]), array([11]), array([12]), array([13]), array([14]), array([15]), array([16]), array([17]), array([18]), array([19]), array([20]), array([21]), array([22]), array([23]), array([24]), array([25]), array([26]), array([27])]
