In [45]:
import numpy as np
a=np.array([6,20,14,26,9,20,11,24,6,21,10,30,14,27,10,28,9,30,6,20,-13,32,7,27,11,30,10,21,7,30,6,32,12,20,8,31,10,21,13,32,12,24,6,22,7,21,13,22,11,24,7,21,8,31,14,30,15,22,10,28,11,26,15,22,11,27,9,22,9,21,14,22,10,30,7,31,11,28,7,30,8,23,7,22,10,26,10,32,8,31,11,26,15,23,8,21,15,21,10,21,9,32,9,25,8,30,8,22,13,30,6,21,4,22,8,20,5,22,3,18,4,20,6,2,20,8,6,19,7,22,3,22,6,21,2,21,3,3,19,4,4,20,7,21,8,21,3,18,7,18,3,3,20,3,4,22,7,21,5,18,7,22,4,20,3,5,18,2,7,18,8,22,-10,21,9,20,8,21,12,71,21,9,11,20,11,18,11,19,12,20,11,19,11,7,20,10,7,20,9,19,11,22,8,21,11,20,12,10,20,8,8,21,12,19,11,19,11,22,11,20,7,10,20,8]).reshape(4,4,7,2)
print(a)

[[[[  6  20]
   [ 14  26]
   [  9  20]
   [ 11  24]
   [  6  21]
   [ 10  30]
   [ 14  27]]

  [[ 10  28]
   [  9  30]
   [  6  20]
   [-13  32]
   [  7  27]
   [ 11  30]
   [ 10  21]]

  [[  7  30]
   [  6  32]
   [ 12  20]
   [  8  31]
   [ 10  21]
   [ 13  32]
   [ 12  24]]

  [[  6  22]
   [  7  21]
   [ 13  22]
   [ 11  24]
   [  7  21]
   [  8  31]
   [ 14  30]]]


 [[[ 15  22]
   [ 10  28]
   [ 11  26]
   [ 15  22]
   [ 11  27]
   [  9  22]
   [  9  21]]

  [[ 14  22]
   [ 10  30]
   [  7  31]
   [ 11  28]
   [  7  30]
   [  8  23]
   [  7  22]]

  [[ 10  26]
   [ 10  32]
   [  8  31]
   [ 11  26]
   [ 15  23]
   [  8  21]
   [ 15  21]]

  [[ 10  21]
   [  9  32]
   [  9  25]
   [  8  30]
   [  8  22]
   [ 13  30]
   [  6  21]]]


 [[[  4  22]
   [  8  20]
   [  5  22]
   [  3  18]
   [  4  20]
   [  6   2]
   [ 20   8]]

  [[  6  19]
   [  7  22]
   [  3  22]
   [  6  21]
   [  2  21]
   [  3   3]
   [ 19   4]]

  [[  4  20]
   [  7  21]
   [  8  21]
   [  3  18]
   [  7  18]
 

In [46]:
a.ndim

4

In [47]:
a.shape

(4, 4, 7, 2)

In [48]:
print(a[:,0])

[[[  6  20]
  [ 14  26]
  [  9  20]
  [ 11  24]
  [  6  21]
  [ 10  30]
  [ 14  27]]

 [[ 15  22]
  [ 10  28]
  [ 11  26]
  [ 15  22]
  [ 11  27]
  [  9  22]
  [  9  21]]

 [[  4  22]
  [  8  20]
  [  5  22]
  [  3  18]
  [  4  20]
  [  6   2]
  [ 20   8]]

 [[  7  18]
  [  8  22]
  [-10  21]
  [  9  20]
  [  8  21]
  [ 12  71]
  [ 21   9]]]


In [49]:
print(a[:,0])   # 3 problem

[[[  6  20]
  [ 14  26]
  [  9  20]
  [ 11  24]
  [  6  21]
  [ 10  30]
  [ 14  27]]

 [[ 15  22]
  [ 10  28]
  [ 11  26]
  [ 15  22]
  [ 11  27]
  [  9  22]
  [  9  21]]

 [[  4  22]
  [  8  20]
  [  5  22]
  [  3  18]
  [  4  20]
  [  6   2]
  [ 20   8]]

 [[  7  18]
  [  8  22]
  [-10  21]
  [  9  20]
  [  8  21]
  [ 12  71]
  [ 21   9]]]


In [50]:
print(a[:,:,1])

[[[14 26]
  [ 9 30]
  [ 6 32]
  [ 7 21]]

 [[10 28]
  [10 30]
  [10 32]
  [ 9 32]]

 [[ 8 20]
  [ 7 22]
  [ 7 21]
  [ 7 21]]

 [[ 8 22]
  [11 18]
  [ 9 19]
  [12 19]]]


In [51]:
l=a[1::2,:,:,1]    # 5 problem
print(l)

[[[22 28 26 22 27 22 21]
  [22 30 31 28 30 23 22]
  [26 32 31 26 23 21 21]
  [21 32 25 30 22 30 21]]

 [[18 22 21 20 21 71  9]
  [20 18 19 20 19  7 10]
  [20 19 22 21 20 10  8]
  [21 19 19 22 20 10  8]]]


In [52]:
l=a[0,:,:,0]   #6 problem
v=l<8
print(l[v])

[  6   6   6 -13   7   7   6   6   7   7]


In [53]:
n=a[1:3,:,:,1] 
c=n>=20
print(n[c])

[22 28 26 22 27 22 21 22 30 31 28 30 23 22 26 32 31 26 23 21 21 21 32 25
 30 22 30 21 22 20 22 20 22 22 21 21 20 21 21 22 21 22 20]
